# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Mobile phone number')),
                ('car_availability', models.BooleanField(default=False, help_text='car_availability_help_text', verbose_name='Car availability')),
                ('address', models.TextField(blank=True, help_text='address_help_text', verbose_name='Adress')),
                ('academic_qualifications', models.CharField(blank=True, max_length=80, verbose_name='Academic qualifications')),
                ('profession', models.CharField(blank=True, max_length=80, verbose_name='Profession')),
                ('volunteer_experience', models.TextField(blank=True, verbose_name='Volunteer Experience')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerComplementaryContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Mobile phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('relation', models.CharField(blank=True, max_length=80, verbose_name='Relation')),
                ('contact_type', models.CharField(choices=[('ICE', 'Contact in Case of Emergency'), ('GAR', 'Guardian'), ('REF', 'Referral')], default='ICE', max_length=3)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
        ),
    ]
