# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, help_text='address_help_text', max_length=120, verbose_name='Adress'),
        ),
    ]
