# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_auto_20161130_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='academic_qualifications',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_experience',
        ),
    ]
