# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_auto_20161201_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(choices=[('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('place', models.CharField(choices=[('FI', 'field'), ('OC', 'operation_center'), ('BO', 'both')], default='FI', max_length=2)),
                ('time_beginning', models.TimeField()),
                ('time_ending', models.TimeField()),
                ('min_volunteers', models.IntegerField()),
                ('max_volunteers', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteercomplementarycontact',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='VolunteerComplementaryContact',
        ),
        migrations.AddField(
            model_name='shift',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Task'),
        ),
    ]
