# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 22:35
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteers', '0006_auto_20161226_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('W', 'Weekly'), ('B', 'Biweekly'), ('M', 'Monthly')], default='W', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='max_volunteers',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='min_volunteers',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set([('task', 'day_of_the_week')]),
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Shift'),
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer'),
        ),
        migrations.AddField(
            model_name='preference',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Shift'),
        ),
        migrations.AddField(
            model_name='preference',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='volunteershift',
            unique_together=set([('volunteer', 'shift')]),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set([('volunteer', 'shift')]),
        ),
    ]
