# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_auto_20161226_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer'),
        ),
    ]
