# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_auto_20161226_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presence', models.BooleanField(default=False)),
                ('volunteer_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.VolunteerShift')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerUnavailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volunteer_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.VolunteerShift')),
            ],
        ),
    ]
