# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='date_of_birth_help_text', null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='mobile_phone_help_text', max_length=128, verbose_name='Mobile phone number'),
        ),
    ]
